// src/redux/cart/cartTypes.js

// Fetch Cart Items
export const CART_FETCH_ITEMS_REQUEST = "CART_FETCH_ITEMS_REQUEST";
export const CART_FETCH_ITEMS_SUCCESS = "CART_FETCH_ITEMS_SUCCESS";
export const CART_FETCH_ITEMS_FAILURE = "CART_FETCH_ITEMS_FAILURE";

// Add Item
export const CART_ADD_ITEM_REQUEST = "CART_ADD_ITEM_REQUEST";
export const CART_ADD_ITEM_SUCCESS = "CART_ADD_ITEM_SUCCESS";
export const CART_ADD_ITEM_FAILURE = "CART_ADD_ITEM_FAILURE";

// Remove Item
export const CART_REMOVE_ITEM_REQUEST = "CART_REMOVE_ITEM_REQUEST";
export const CART_REMOVE_ITEM_SUCCESS = "CART_REMOVE_ITEM_SUCCESS";
export const CART_REMOVE_ITEM_FAILURE = "CART_REMOVE_ITEM_FAILURE";