// Fetch All Products
export const PRODUCT_FETCH_REQUEST = "PRODUCT_FETCH_REQUEST";
export const PRODUCT_FETCH_SUCCESS = "PRODUCT_FETCH_SUCCESS";
export const PRODUCT_FETCH_FAILURE = "PRODUCT_FETCH_FAILURE";

// Fetch Single Product
export const PRODUCT_FETCH_SINGLE_REQUEST = "PRODUCT_FETCH_SINGLE_REQUEST";
export const PRODUCT_FETCH_SINGLE_SUCCESS = "PRODUCT_FETCH_SINGLE_SUCCESS";
export const PRODUCT_FETCH_SINGLE_FAILURE = "PRODUCT_FETCH_SINGLE_FAILURE";